email_address: example@gmail.com
domain: example.co.uk
password: password
articles_slug: news
category_slug: category
site_url: http://example.co.uk/
site_title: One More roroacms website
display_url: http://www.example.co.uk/
tag_slug: tag
admin_email: example@gmail.com
admin_username: admin
admin_password: password
theme_folder: roroa-bootstrap-3