development:
email_address: simonfletcher0@gmail.com
domain: simon-fletcher.me
password: beahiexie
articles_slug: news
category_slug: category
site_url: http://localhost:3000/
site_title: One More roroacms website
display_url: http://www.simon-fletcher.me/
tag_slug: tag
admin_email: simonfletcher0@gmail.com
admin_password: 123123
admin_username: admin
aws_access_key_id: AKIAI4VD2NT6NMGJLCOQ
aws_secret_access_key: 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
aws_bucket_name: roroa
theme_folder: roroa1
test:
email_address: simonfletcher0@gmail.com
domain: simon-fletcher.me
password: beahiexie
articles_slug: news
category_slug: category
site_url: http://localhost:3000/
site_title: One More roroacms website
display_url: http://www.simon-fletcher.me/
tag_slug: tag
admin_email: simonfletcher0@gmail.com
admin_password: 123123
admin_username: admin
aws_access_key_id: AKIAI4VD2NT6NMGJLCOQ
aws_secret_access_key: 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
aws_bucket_name: roroa
theme_folder: roroa1
production:
email_address: simonfletcher0@gmail.com
domain: simon-fletcher.me
password: beahiexie
articles_slug: news
category_slug: category
site_url: http://localhost:3000/
site_title: One More roroacms website
display_url: http://www.simon-fletcher.me/
tag_slug: tag
admin_email: simonfletcher0@gmail.com
admin_password: 123123
admin_username: admin
aws_access_key_id: AKIAI4VD2NT6NMGJLCOQ
aws_secret_access_key: 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
aws_bucket_name: roroa
theme_folder: roroa1


